packages:
  - docs

catalog:
  "@pagefind/default-ui": ^1.5.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1

catalogMode: prefer
overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
